version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/process-pension-44:2"
        LoadBalancerInfo:
          ContainerName: "process-pension"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"